#! /bin/bash

# run this script as "topn n log.txt"
numberRows=$(cut -d '"' -f1,4 $2 | grep -v '"-' | cut -d ' ' -f1 | sort | uniq -c | sort -n -r | head -$1 | awk '{sum+=$1} END {print sum}')
asnwer=$(cut -d '"' -f1,4 $2 | grep -v '"-' | cut -d ' ' -f1 | sort | uniq -c | sort -n -r | head -$1 | awk '{printf(NR ". %s - %d - %.1f%% \n", $2, $1, $1 / '"$numberRows"' * 100)}')

echo "$asnwer
